### PR TITLE
Update to 1.17

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Do not merge this while it is a draft, this is just to keep track of updates. I will mark as 'ready for review' when 1.17 is fully released, and will constantly update to pre-releases/release-candidates until then.

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
pre-3 did not need mappings changes, but some updates might

**Comment by DragonEggBedrockBreaking** [comment]
pre-release 4 now

**Comment by DragonEggBedrockBreaking** [comment]
pre-release 5 now

**Comment by DragonEggBedrockBreaking** [comment]
release-candidate 1 now

**Comment by Siuolplex** [comment]
How did I not notice this exists?
Im marking it as ready for review, as I dont think full will change anything and Ill fix anything that needs fixing. (And def not because I hit button and I was curious on it.)

**Comment by Siuolplex** [comment]
Looks perfect! Sorry about being curious there, but feel free to update when 1.17 fully hits

**Comment by DragonEggBedrockBreaking** [comment]
Ready for merge

**Comment by Siuolplex** [comment]
Just saw this, I shall merge this, good work DragonEgg. (PS: Tell the caffine staff to give me the whitelist to chat in the development chats please /s but not really)

**Pull request merged**
